VERBOSE = True
FPS = 24
SCREEN_SIZE = 240, 160
DEFAULT_CAPTION = "Battleships!"
SHIP_COLOUR = 8
PLAYER_COLOUR = 11
ENEMY_COLOUR = 9
DEAD_SHIP_COLOUR = 10
SHOT_COLOUR = 5
TEXT_COLOUR = 12
#DEFAULT_SCALE
#DEFAULT_PALETTE
#DEFAULT_FPS
#DEFAULT_BORDER_WIDTH