VERBOSE = False
FPS = 24
SCREEN_SIZE = 240, 160
DEFAULT_CAPTION = "Battleships!"
BACKGROUND_COLOUR = 0
SHIP_COLOUR = 1
HUMAN_COLOUR = 2
ENEMY_COLOUR = 3
DEAD_SHIP_COLOUR = 4
SHOT_COLOUR = 5
TEXT_COLOUR = 6
GRID_COLOUR = 7
SHIP_LENGTHS = [2,3,4,5]

#DEFAULT_SCALE
#DEFAULT_PALETTE
#DEFAULT_FPS
#DEFAULT_BORDER_WIDTH